"""
Quick script to create .env file with your API keys
Run this to easily set up your environment
"""

import os
from pathlib import Path

def create_env_file():
    """Create .env file with user's API keys."""
    
    print("=" * 70)
    print("  🚀 Intelligent Interruption Handling - Environment Setup")
    print("=" * 70)
    print("\nThis script will help you create your .env file.")
    print("You'll need 4 FREE API keys (takes ~10 minutes to get all):\n")
    
    print("1. LiveKit Cloud - https://cloud.livekit.io")
    print("2. Groq (LLM) - https://console.groq.com ⭐ FASTEST & FREE")
    print("3. Deepgram (STT) - https://deepgram.com")
    print("4. Cartesia (TTS) - https://cartesia.ai")
    print()
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/n): ").lower()
        if overwrite != 'y':
            print("Cancelled. Your existing .env file is unchanged.")
            return
        print()
    
    print("Let's set up your API keys:\n")
    print("-" * 70)
    
    # Get API keys
    print("\n📍 LIVEKIT CLOUD")
    print("Get from: https://cloud.livekit.io")
    livekit_url = input("LIVEKIT_URL (wss://...): ").strip()
    livekit_key = input("LIVEKIT_API_KEY: ").strip()
    livekit_secret = input("LIVEKIT_API_SECRET: ").strip()
    
    print("\n📍 GROQ (LLM)")
    print("Get from: https://console.groq.com")
    groq_key = input("GROQ_API_KEY (gsk_...): ").strip()
    
    print("\n📍 DEEPGRAM (STT)")
    print("Get from: https://deepgram.com")
    deepgram_key = input("DEEPGRAM_API_KEY: ").strip()
    
    print("\n📍 CARTESIA (TTS)")
    print("Get from: https://cartesia.ai")
    cartesia_key = input("CARTESIA_API_KEY (or press Enter to skip): ").strip()
    
    print("\n📍 OPTIONAL: ElevenLabs (Alternative TTS)")
    elevenlabs_key = input("ELEVENLABS_API_KEY (or press Enter to skip): ").strip()
    
    # Create .env content
    env_content = f"""# Intelligent Interruption Handling - API Keys
# Generated by create_env.py

# LiveKit Cloud
LIVEKIT_URL={livekit_url}
LIVEKIT_API_KEY={livekit_key}
LIVEKIT_API_SECRET={livekit_secret}

# Groq (LLM - Brain)
GROQ_API_KEY={groq_key}

# Deepgram (STT - Speech to Text)
DEEPGRAM_API_KEY={deepgram_key}
"""
    
    if cartesia_key:
        env_content += f"\n# Cartesia (TTS - Text to Speech)\nCARTESIA_API_KEY={cartesia_key}\n"
    
    if elevenlabs_key:
        env_content += f"\n# ElevenLabs (Alternative TTS)\nELEVENLABS_API_KEY={elevenlabs_key}\n"
    
    # Write to file
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print("\n" + "=" * 70)
        print("✅ SUCCESS! .env file created!")
        print("=" * 70)
        print("\nYour API keys have been saved to: .env")
        print()
        print("Next steps:")
        print("1. Run automated tests:")
        print("   python test_implementation.py")
        print()
        print("2. Start the agent:")
        print("   python examples/voice_agents/test_interrupt_free.py dev")
        print()
        print("3. Test all scenarios (see FINAL_SETUP_AND_TEST.md)")
        print()
        print("🎉 Ready to test intelligent interruption handling!")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        print("\nYou can manually create .env file using env_template.txt")


if __name__ == "__main__":
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n\nError: {e}")
        print("\nYou can manually create .env file using env_template.txt")

