SOFT_WORDS: set[str] = {
    "yeah",
    "yea",
    "yah",
    "ya",
    "yeaah",
    "yeahh",
    "yep",
    "yup",
    "yes",
    "yess",
    "okay",
    "ok",
    "okey",
    "okk",
    "kay",
    "k",
    "kk",
    "okaay",
    "alright",
    "all right",
    "aight",
    "sure",
    "for sure",
    "sure thing",
    "uh-huh",
    "uh huh",
    "uhuh",
    "mm-hmm",
    "mm hmm",
    "mmhmm",
    "mhm",
    "mmm",
    "hmm",
    "hm",
    "hmmm",
    "uh",
    "uhh",
    "uhhh",
    "um",
    "umm",
    "ummm",
    "ah",
    "ahh",
    "oh",
    "ohh",
    "right",
    "rite",
    "i see",
    "i got it",
    "got it",
    "gotcha",
    "makes sense",
    "understood",
    "copy that",
    "all good",
    "perfect",
    "nice",
    "cool",
    "great",
    "awesome",
    "interesting",
    "no problem",
    "you're right",
    "that's right",
    "i agree",
    "totally",
    "exactly",
    "absolutely",
    "definitely",
    "indeed",
    "quite",
    "go ahead",
    "please continue",
    "go on",
    "continue",
}

HARD_WORDS: set[str] = {
    "wait",
    "hold on",
    "stop",
    "pause",
    "hold it",
    "hold up",
    "no",
    "nope",
    "don't",
    "don't do that",
    "cancel",
    "never mind",
    "never",
    "forget it",
    "ignore that",
    "skip that",
    "skip it",
    "back up",
    "rewind",
    "again",
    "repeat",
    "slower",
    "faster",
    "louder",
    "quieter",
    "quieter please",
    "speak up",
    "what",
    "huh",
    "pardon",
    "come again",
    "say again",
    "say that again",
    "redo",
    "change that",
    "different",
    "something else",
    "alternative",
    "try again",
    "one more time",
    "rephrase",
    "rephrase that",
    "explain",
    "clarify",
    "say it differently",
    "summarize",
    "start over",
    "begin again",
    "let's start over",
    "restart",
}                                   